### ISSUE TITLE
Update `@font-face`, add alternate font formats

### ISSUE THREAD

**Issue by mysterycommand** [potpiedigital/poetspetparlor.com#10]
As I was trying to explain, different browsers support different font formats. Just having a TTF is not going to be enough to work across all browsers. Luckily other people have solved this problem for us … see Paul Irish's [Bulletproof `@font-face` Syntax](https://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/) for a thorough run down of the issues involved, or just skip straight to Font Squirrel's [Webfont Generator](https://www.fontsquirrel.com/tools/webfont-generator) where you can upload your TTF and get a ZIP file with alternate file formats and a text snippet to use for your `@font-face` declaration in your CSS.

You'll also have to add the new file formats to the copy task, but if you get the above done before our meeting on Thursday I can walk you through this part.

**Comment by Purple906** [comment]
I think this is already fixed, unless I did it wrong but the woff files in the @font-face syntax is what the webfont generator gave me.

**Comment by Purple906** [comment]
If this is still an issue I can reopen but I think its done? @mysterycommand
