### ISSUE TITLE
Footer links look weird sometimes

### ISSUE THREAD

**Issue by mysterycommand** [potpiedigital/poetspetparlor.com#14]
Depending on what size you're at, the footer links don't always line up right. Need to handle for 3 cases: 1. desktop - they all fit next to each other on a row, 2. big-phone/tablet - they fit with the map on one "line" and the two lists in a row on the next line, and 3. each one is stacked on top of the other in a column.

<img width="334" alt="screenshot 2016-10-03 18 11 56" src="https://cloud.githubusercontent.com/assets/810398/19059525/55743a36-8995-11e6-8fb4-4796feb6c1c5.png">

<img width="421" alt="screenshot 2016-10-03 18 12 07" src="https://cloud.githubusercontent.com/assets/810398/19059526/5578a454-8995-11e6-8fcf-a98fbfc2c55b.png">

**Comment by Purple906** [comment]
did adjustments and tested in inspector, phone and tablets both portrait and landscape. Decided to adjust the iframe over others.
