### ISSUE TITLE
dog-dividers

### ISSUE THREAD

**Issue by Purple906** [potpiedigital/poetspetparlor.com#18]
So I tried to export the dog dividers from sketch (after removing the box shadow) as svg files but when I incorporated them into the website the images where blurry (I assume suffering from the same issue the logo is).

So re-exported them as png files then used css to create the drop shadow, in hopes of fixing the slight offset issue when viewed in mobile. but the drop shadow is now showing up on the square img instead of the circle. 

I assume the fix is to make the svg export correctly, but that kind of ties into issue #17 so kind of two problems in one. @mysterycommand

**Comment by mysterycommand** [comment]
Is this still a thing? I think no, but just wanted to double check.
